name: Build Kernel
on:
  push:
    branches:    
      - ElementalX

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/pvapor/marlin.git --depth=1 
    - name: Build With Shell
      run: |
        cd ~/marlin
        sudo bash build.sh
    - name: Package With AnyKernel
      run: |
        cd ~
        cp marlin/AnyKernel ./ -r
        cd AnyKernel/
        cp ../marlin/out/arch/arm64/boot/Image.gz-dtb  ./
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: marlin.zip
        path: /home/runner/AnyKernel/
